# Generated by Django 3.2.9 on 2021-12-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.AutoField(primary_key=True, serialize=False)),
                ('cuentaJardinero', models.CharField(max_length=60)),
                ('idPublicacion', models.CharField(max_length=120)),
                ('cuentaCliente', models.CharField(max_length=60)),
                ('fechaReserva', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
