# Generated by Django 3.2.9 on 2022-02-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='idPublicacion',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
